on: create

name: Release
permissions: write-all
jobs:
  release:
    name: Release GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/release-github-actions@v8
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CREATE_MAJOR_VERSION_TAG: true
          CREATE_MINOR_VERSION_TAG: true
